apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  project: app
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 48.2.2
    helm:
      values: |-
        prometheus-node-exporter:
          hostRootFsMount:
            enabled: false
          prometheusOperator:
            admissionWebhooks:
              failurePolicy: Ignore
        grafana:
          enabled: true
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: nginx
            hosts:
            - grafana.hkaibara.net
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - ServerSideApply=true
    - CreateNamespace=true